mrc-ide/rrq

.Rbuildignore
.gitignore
.travis.yml
DESCRIPTION
R/expression.R
R/rrq_controller.R
R/time.R
R/utils.R
R/worker.R
R/worker_messages.R
R/worker_run.R
R/worker_spawn.R
README.md
appveyor.yml
tests/testthat/helper-rrq.R
tests/testthat/test-expression.R
tests/testthat/test-message.R
tests/testthat/test-rrq.R
tests/testthat/test-time.R
tests/testthat/test-worker-config.R
tests/testthat/test-worker-spawn.R

This PR removes use of the `context` and `queuer` packages from `rrq`.  Doing this will allow us to do two things:
* submit the package to CRAN without worrying about a long dependency chain
* re-implement the bulk submission (`lapply` - like interface) in a way that fits better with the new environment creation
The bulk of the new code here was directly copied in from `context` / `queuer` with simplifications to remove unused code branches.  The code in `expression.R` will change when we do bulk submission, and includes a couple of options that are not (yet) exposed to `enqueue`. The progress bar bits are all a bit tedious, but nice for interactive use.

MRC-538: remove use of context/queuer

---

R/heartbeat.R
R/rrq_controller.R
R/utils_assert.R
R/worker.R
R/worker_config.R
R/worker_run.R
R/worker_runner.R
R/zzz.R
man/rrq_worker.Rd
tests/testthat/test-utils.R
tests/testthat/test-worker-config.R

* verbosity should be a property of the worker
* there are more pipelineable commands
* we should not query redis for our own active task
These bookkeeping changes underly mrc-600 and mrc-558 but make them harder to understand if not done separately

MRC-601: refactor worker

---

DESCRIPTION
NEWS.md
R/rrq_controller.R
R/worker_run.R
tests/testthat/helper-rrq.R
tests/testthat/test-rrq.R
tests/testthat/test-zzz-fault-tolerance.R

This PR adds support for cancelling tasks.  It's somewhat delicate due to the potential for race conditions and cancelling the wrong task, and that is explained above the implantation.

MRC-734: Support for cancelling tasks

---

DESCRIPTION
NEWS.md
R/rrq_controller.R
tests/testthat/test-rrq.R

This PR prevents an uninformative error while cancelling a non-existant task, replacing it with an informative one. Previously we saw:
```r
obj <- test_rrq()
id <- ids::random_id()
obj$task_cancel(id)
```
Here, we add a status (`TASK_MISSING`) if called with a nonexistant task, and the error will come out as
```
Task abcdef0123456789 is not running (MISSING)"
```
which is consistent with the case when cancelling a complete task
```
Task abcdef0123456789 is not running (COMPLETE)"
```

mrc-1259: Better error message when cancelling non-existant task

---

DESCRIPTION
NEWS.md
R/rrq_controller.R
tests/testthat/test-rrq.R

This is required to support mrc-1301 in hintr and the interface might change a little. I want to be able to, given a task id, get the expression and local variables for that task.

MRC-1304: Get debug information out of rrq

---

DESCRIPTION
NEWS.md
R/worker_runner.R
tests/testthat/test-rrq-workers.R

Looks like this was caused by the docopt breaking change (translating hyphens to underscores). That meant that `--key-alive` was coming through as `key_alive`. We then pass along `dat[["key-alive"]]` which is `NULL` and the worker does not post back to say they're alive, despite clearly being up!
I've taken the same approach as with orderly and doing the to-underscore translation ourselves so that this works with old and new docopt, plus added a test for argument passing.

mrc-1667: Fix worker spawn

---

DESCRIPTION
NEWS.md
R/rrq_controller.R
man/rrq_controller.Rd
man/rrq_task_progress_update.Rd
man/rrq_worker.Rd
man/worker_spawn.Rd
tests/testthat/test-rrq.R

In preparation to pick #17 up again, this PR adds roxygen docs to the main class. We need examples and a vignette still.
Minimal changes to the actual implementation aside from dropping a couple of arguments that were not used.

mrc-1800: Expand docs

---

DESCRIPTION
NEWS.md
R/bulk.R
R/common.R
R/keys.R
R/rrq_controller.R
R/worker.R
R/worker_config.R
R/worker_runner.R
man/rrq_controller.Rd
man/rrq_worker.Rd
tests/testthat/test-bulk.R
tests/testthat/test-rrq.R
tests/testthat/test-zzz-fault-tolerance.R

Basic support for multiple queues within an rrq object. When workers are created a vector of queues (indicated by names) can be specified - they listen to these in descending order.
This is inadequately tested at the moment:
* tests for the affected query methods with multiple jobs on multiple queues
* good tests for the deletion, which is bad enough as it is

mrc-2068: Support for multiple queues

---

DESCRIPTION
NEWS.md
R/rrq_controller.R
man/rrq_controller.Rd
rrq.Rproj
tests/testthat/test-rrq.R

This is info we want to return in orderly.server refactor https://github.com/vimc/orderly.server/pull/35 but I thought would be generally useful. 
Thoughts on function name? I'm trying to follow pattern of naming on the controller but couldn't think of an amazing name for this. `task_preceeding_tasks`? `queue_preceeding_tasks` something like this maybe better? `queued_tasks`?

Add function to queue to list tasks in front of a particular task

---

.github/workflows/test-coverage.yaml
DESCRIPTION
NEWS.md
R/bulk.R
R/keys.R
R/rrq_controller.R
R/worker.R
R/worker_run.R
man/rrq_controller.Rd
tests/testthat/myfuns.R
tests/testthat/test-rrq-progress.R
tests/testthat/test-rrq.R

This PR adds the ability to run a worker job in a transient process using callr. It is incomplete, but you can try it out in hintr before we finish it. The interface is an argument `separate_process = TRUE` to functions like `$enqueue()`.
* I am not completely sold on `separate_process = TRUE` as a name; we also use "local" for the key (much shorter) and "remote" to describe the separate process. However, what argument we expose should have a default of `FALSE` as these are easier to understand.
* The testing is extremely minimal and does not actually make sure that the job even ran on a different process! ~We need to include some tests that logging works as expected at least as that was the motivation for this, but we might also write a function that pollutes the global environment~
* …

mrc-2068: Add support for sending to external processes

---

DESCRIPTION
R/dependencies.R
R/keys.R
R/rrq_controller.R
R/worker.R
tests/testthat/test-bulk.R
tests/testthat/test-rrq.R

This PR will
* Add 1 deferred "queue" - really this is a set of deferred tasks (previously 1 per queue type)
* When a deferred task gets put onto queue it will be put onto the queue set at submission time

mrc-2270: Deferred tasks get added to correct queue

---

tests/testthat/test-rrq.R

I mentioned a case where we had task A, B added to queue and C which depends on A & B.
If A failed, it would mark C as impossible
But if B completed successfully then it would put A onto the queue
So I had a test for this which I had removed temporarily which I definitely saw failing, but since adding this test back in it is now working. So I think some code change has fixed this too. Which makes sense because we would only remove A from the list of dependencies of C in the case that it A completes successfully. So what happens is
A fails, marks C as impossible
B completes, checks if it can queue C but it cannot because task A is still in list of dependencies (and will never be removed)
Still good to add the test for this

mrc-2267: Add test to check impossible task cannot be put onto queue

---

DESCRIPTION
R/dependencies.R
R/rrq_controller.R
tests/testthat/test-rrq.R

* Deferred tasks can be cancelled & deleted
* Tasks cancelled which have dependencies will mark these as impossible (where they cannot be resolved)

mrc-2268: Add support for delete & cancelling tasks with dependencies and deferred tasks

---

R/bulk.R
R/common.R
R/keys.R
R/rrq_controller.R
R/worker_run.R
man/rrq_controller.Rd
tests/testthat/test-bulk.R
tests/testthat/test-rrq.R
tests/testthat/test-zzz-fault-tolerance.R

This will be used by orderly.server; only works for tasks sent to a different process, but that's fine for our use there.

mrc-2341: allow timeout for tasks submitted to separate process

---

DESCRIPTION
NEWS.md
R/bulk.R
R/expression.R
R/rrq_controller.R
R/utils_assert.R
man/rrq_controller.Rd
tests/testthat/test-expression.R
tests/testthat/test-rrq.R
tests/testthat/test-utils.R

This PR adds support for explicitly listing variables copied over with an expression.
This is required to support future where the analysis of variables is already done, and the "user" in this case specifies name/value pairs needed for the remote calculation.
At the same time this tidies up some unneeded/unexposed complication in the expression analysis code
~Rebase on #39 once it's merged.~

mrc-2369: control over exported variables

---

DESCRIPTION
NEWS.md
R/keys.R
R/rrq_controller.R
R/worker_run.R
man/rrq_controller.Rd
tests/testthat/test-rrq.R

This PR eliminates the need for a "busy wait" for tasks to complete by making every task get a list that can be used with `BLPOP`. This should reduce the chattiness of the system and make returning tasks slightly faster.
~Merge after #43~

mrc-2392: Always allow blocking wait for task

---

.Rbuildignore
.hadolint.yaml
DESCRIPTION
docker/Dockerfile
tests/testthat/helper-rrq.R
tests/testthat/test-bulk-support.R
tests/testthat/test-bulk.R
tests/testthat/test-configure.R
tests/testthat/test-expression.R
tests/testthat/test-message.R
tests/testthat/test-migrate.R
tests/testthat/test-object-store.R
tests/testthat/test-redis.R
tests/testthat/test-rrq-progress.R
tests/testthat/test-rrq-workers.R
tests/testthat/test-rrq.R
tests/testthat/test-time.R
tests/testthat/test-utils.R
tests/testthat/test-worker-config.R
tests/testthat/test-worker-spawn.R
tests/testthat/test-zzz-fault-tolerance.R
tests/testthat/test-zzz-heartbeat.R

Maintenance PR to port to testthat 3e (see https://testthat.r-lib.org/articles/third-edition.html)

Port to use testthat v3

---

DESCRIPTION
R/configure.R
tests/testthat/test-configure.R

This just tripped me and @RaphaelS1 up; if identical configurations are set, that should be a no-op so that scripts don't need to guess if it's needed or not.

Allow resetting identical configuration

---

DESCRIPTION
R/envir.R
R/heartbeat_impl.R
R/rrq_controller.R
README.Rmd
README.md
extra/benchmark.Rmd
man/heartbeat_kill.Rd
man/rrq_controller.Rd
man/rrq_envir.Rd
tests/testthat/helper-rrq.R
tests/testthat/test-bulk.R
tests/testthat/test-migrate.R
tests/testthat/test-rrq.R
tests/testthat/test-utils.R
vignettes/messages.Rmd
vignettes/rrq.Rmd
vignettes_src/messages.Rmd
vignettes_src/rrq.Rmd

This PR removes the helper `rrq_controller()` function and instead uses the R6 constructor directly.
I've not added any compatibility helpers (unlike in https://github.com/mrc-ide/odin/pull/227) as the current user list is small enough that we can patch them up directly.
Once merged, update:
* https://github.com/mrc-ide/hintr/pull/291
* https://github.com/mrc-ide/didehpc/pull/98
The spimalot PR will work with either version

Use R6 constructors directly

---

DESCRIPTION
R/rrq_controller.R
R/utils.R
man/rrq_controller.Rd

This moves from x, fun to X, FUN which avoids argument consumption when the function takes 'x' as an argument:
```
f <- function(x, fun, ...) {
lapply(x, fun, ...)
}
g <- function(x, y) {
x + y
}
f(1:10, g, x = 2)
#> Error in get(as.character(FUN), mode = "function", envir = envir) : 
#>   object 'fun' of mode 'function' was not found
```

Move from x, fun => X, FUN in interface

---

DESCRIPTION
R/worker_messages.R
tests/testthat/test-message.R
tests/testthat/test-migrate.R
vignettes/messages.Rmd
vignettes_src/messages.Rmd

This constantly trips (tripped) me up; if you have a worker with a timeout - typical for the cluster - then sending a message does not reset the timer.  With this PR most messages do reset the timer except for ones that would make no sense

Most messages now reset timer

---

.github/workflows/test-coverage.yaml
DESCRIPTION
R/keys.R
R/rrq_controller.R
R/utils.R
R/worker_run.R
extra/.gitignore
extra/Makefile
extra/benchmark.Rmd
extra/requirements.txt
man/rrq_controller.Rd
tests/testthat/test-rrq.R

This does incur a small extra overhead but it's not that bad, and seems to disappear when you add a few workers.
This PR:
* tides up the incredibly out of date benchmarking
* adds support for saving times out
There are 3 reliable times we can get - the time of submission (perhaps that is uninteresting?), the time of task start (we know we want that!) and the time of task finishing.  These are saved into 3 hashes at the points where we save job status back, which are all quite nicely defined.
Very open to new names (start/submit/complete), drawing a blank on something better

Store times alongside tasks

---

DESCRIPTION
R/bulk.R
R/common.R
R/dependencies.R
R/rrq_controller.R
R/task_cleanup.R
R/worker_run.R
tests/testthat/test-bulk-support.R
tests/testthat/test-common.R
tests/testthat/test-rrq.R
tests/testthat/test-zzz-fault-tolerance.R

This PR will
* Add some useful groupings of tasks, e.g. TASK$waiting and use these in logic which should help minimise the amount of changes we need to add a new status at any point
* Add a helper for running task cleanup
* Call this when tasks set impossible to make sure task result is saved out so that `task_wait` works for IMPOSSIBLE tasks
* Add test to check that `task_wait` works with IMPOSSIBLE

Fix task wait

---

DESCRIPTION
NEWS.md
R/common.R
R/worker.R
tests/testthat/test-common.R
tests/testthat/test-rrq-workers.R
tests/testthat/test-utils.R

This PR will
* Update `rrq_version` returned in `worker_info` to report only the rrq version number. Removing additional info previously returned about sha & repository

Update rrq_version on worker_info to report version number only

---

DESCRIPTION
NEWS.md
R/rrq_controller.R
man/rrq_controller.Rd
tests/testthat/test-rrq.R
vignettes/rrq.Rmd
vignettes_src/rrq.Rmd

As discussed, this is now unused and inelegant.
~Merge after #74, contains those commits~

mrc-4069: drop at_front from queue submission

---

R/rrq_controller.R
README.Rmd
README.md
man/rrq_controller.Rd
tests/testthat/helper-rrq.R
tests/testthat/test-bulk.R
tests/testthat/test-configure.R
tests/testthat/test-object-store.R
tests/testthat/test-redis.R
tests/testthat/test-rrq-workers.R
tests/testthat/test-rrq.R
tests/testthat/test-time.R
tests/testthat/test-worker-spawn.R
tests/testthat/test-zzz-fault-tolerance.R
vignettes/messages.Rmd
vignettes/rrq.Rmd
vignettes_src/messages.Rmd
vignettes_src/rrq.Rmd

This PR updates the test and vignette running to ensure that no remaining R processes or keys are left in the redis database. This was a bit of a fiddle to do! I was going to work on mrc-4065 (clean up workers) but feel like this was really needed first.

Make cleanup deterministic and thorough

---

DESCRIPTION
NEWS.md
R/rrq_controller.R
man/rrq_controller.Rd
tests/testthat/helper-rrq.R
tests/testthat/test-rrq.R
tests/testthat/test-zzz-rrq.R

~Merge after #80, contains those commits.~
This PR allows tuning of the default task wait timeout in two places:
* globally with the option `rrq.timeout_task_wait`
* at the `rrq_controller` level with the `timeout_task_wait` argument
It is overrideable at the point of retrieval

Better task fetch timeout control

---

DESCRIPTION
tests/testthat/helper-rrq.R

As discussed last week, adds a little helper to the tests to skip if the installed version does not match on the version number.

Helper to verify that locally installed rrq is suitable

---

DESCRIPTION
NEWS.md
R/keys.R
R/rrq_controller.R
R/utils.R
R/worker_run.R
man/rrq_controller.Rd
tests/testthat/test-rrq.R

Pretty simple at first, just returning a few things in a list. This *will* expand because it would be nice to return information about the dependency structure and retry chain here, but starting simple for now

Add new task_info method

---

DESCRIPTION
Makefile
R/heartbeat.R
R/rrq_controller.R
tests/testthat/test-zzz-fault-tolerance.R
vignettes/fault-tolerance.Rmd
vignettes/rrq.Rmd
vignettes_src/fault-tolerance.Rmd
vignettes_src/fault.R

This will get expanded once we get support for retrying tasks, but provides the context for that.
I've also fixed a weird bug that I thought we had an issue for (but can't find) where task_result on jobs that were lost via worker death and separate process death were not the same - now we always return an rrq_task_error

Add fault tolerance vignette

---

DESCRIPTION
R/dependencies.R
R/keys.R
R/rrq_controller.R
R/task_cleanup.R
tests/testthat/test-bulk.R
tests/testthat/test-rrq-retry.R
tests/testthat/test-rrq.R

This PR simplifies handling of querying dependencies:
* dependents/dependencies becomes "depends down" and "depends up", reflecting moved up and moved down in the task retrying
* add information about dependencies to the task info
* remove the deferred set in favour of computing this at the point of asking

Simplify dependency handling

---

DESCRIPTION
R/dependencies.R
R/heartbeat.R
R/rrq_controller.R
R/task_cleanup.R
R/utils.R
R/worker_run.R
tests/testthat/test-rrq.R

This PR tidies up how we do dependency handling, ahead of refactoring to use lua scripts for most of it. In particular, there are no mutually recursive calls any more, with the only bit of recursion being the dependency finding.
This was much more fiddly to write than the line count suggests, and has at least one visible change in behaviour - cancelling a task no longer deletes it (this was a very odd choice, not sure why we'd have wanted that)

Consistent, nonrecursive, dependency handling

---

DESCRIPTION
R/worker.R
R/worker_run.R

Things I noticed elsewhere but didn't want to put into other PRs, as we never use either the cancel key or the key_complete as pulled here. I've tidied up the "active task" to be just the task id, too.

Tidy up worker run

---

DESCRIPTION
R/expression.R
tests/testthat/funs-bulk.R
tests/testthat/test-bulk.R
tests/testthat/test-expression.R

The issue here is sort of described in the issue (#98) and in the test case. Basically, in the most common real-world situation (functions sourced globally) any function we use via lapply or enqueue bulk ends up with an environment that means that it cannot find any values referred to using lexical scope! I think that callr does this nicely by passing in the `package` environment, it's a hard problem really.
Here, we just fix up the environments of any functions that come through anonymously.
Fixes #98

Fix environment bug in bulk submission

---

.lintr
tests/testthat/myfuns.R

There's a new lintr version, and it has a well-meaning but (IMO) poorly implemented indentation linter. It might get there in the end, but needs disabling here or just adds noise

Fix lints with newer lintr

---

DESCRIPTION
R/rrq_controller.R
R/rrq_task.R
R/time.R
man/rrq_task_exists.Rd
man/rrq_task_results.Rd
man/rrq_task_status.Rd
tests/testthat/test-rrq-task.R
tests/testthat/test-rrq.R

Small one; just allows return types not to be named, which is consistent with hipercow.  This will makes the docs a bit easier to write.  I've left the behaviour unchanged for the legacy controller.

Allow not naming return values from most functions

---

R/worker.R
R/worker_run.R
man/rrq_task_overview.Rd
man/rrq_worker.Rd
tests/testthat/test-rrq.R

For orderly runner we would like the worker to know its own worker id since our file structure in the orderly root is `.packit/workers/<worker-id>`.

Add basic env variables to every worker

---

DESCRIPTION
R/worker_run.R
tests/testthat/test-rrq-progress.R

Code change is very small: we just need to register a handler for the progress condition and then zap it once handled.
The test change is weirder; I've duplicated the code for the old-style tests and then changed all controller uses to use free functions.  There's one test there that is clearly in the wrong file.
Before zap() was added I got the same error we saw in hintr, so pretty sure this is right. I'll update the hintr PR to point at this branch and see what happens...

Progress handling for new-style task running

---

DESCRIPTION
README.Rmd
README.md

I noticed this when working with Cosmo. 
Reordering the description is a vain attempt to get autolinking from hipercow working - see https://pkgdown.r-lib.org/articles/linking.html - the issue here is that https://mrc-ide.github.io/hipercow/reference/hipercow_rrq_controller.html does not link to our site but to the rdrr.io site.  We may have to manually update hipercow links if we can't get that working...

Small doc fixes

---

DESCRIPTION
R/worker_run.R
R/worker_spawn.R

it is suggested by processx documentation that we use `2>&1` to redirect `stderr` to the same file as `stdout`. https://processx.r-lib.org/reference/process.html#method-process-new so just made this change in the relevant places

stderr logging fix

---

DESCRIPTION
R/worker_run.R
tests/testthat/test-rrq.R

When a task is run in a separate process, a new rrq_worker object and controller are created in the sub-process. These need to be configured to use the right offload directory.
It's not obvious to me that the sub-process even needs to interact with Redis and the offload directory. It could very well let the main worker process load the task data and receive it in its arguments, letting callr handle the transfer. In fact that's already how the result is handled, it get returned by the subprocess and written to the offload storage by the parent process.

Propagate the offload path to sub-processes.
